"use client";

import { ChangeEvent, FormEvent, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

const channels = [{id:"facebook",label:"Facebook"},{id:"instagram",label:"Instagram"},{id:"linkedin",label:"LinkedIn"},{id:"google_business",label:"Google Business"}];
function value(form: FormData, key: string) { const entry=form.get(key); return typeof entry === "string" ? entry.trim() : ""; }

export default function NewPostPage() {
 const [selected,setSelected]=useState(["facebook","instagram","linkedin","google_business"]); const [mediaUrl,setMediaUrl]=useState(""); const [mediaPublicId,setMediaPublicId]=useState(""); const [mediaType,setMediaType]=useState<"image"|"video">("image"); const [uploading,setUploading]=useState(false); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
 function toggle(id:string){setSelected((current)=>current.includes(id)?current.filter((x)=>x!==id):[...current,id]);}
 async function uploadMedia(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0]; if(!file)return; const type=file.type.startsWith("video/")?"video":"image"; setMediaType(type);setUploading(true);setError("");try{const supabase=createSupabaseBrowserClient();const {data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token){location.href="/login";return;}const signResponse=await fetch("/api/cloudinary/sign",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({})});const signed=await signResponse.json();if(!signResponse.ok)throw new Error(signed.error||"Unable to prepare upload");const upload=new FormData();upload.append("file",file);upload.append("api_key",signed.apiKey);upload.append("timestamp",String(signed.timestamp));upload.append("signature",signed.signature);upload.append("folder",signed.folder);const resourceType=type==="video"?"video":"image";const response=await fetch(`https://api.cloudinary.com/v1_1/${signed.cloudName}/${resourceType}/upload`,{method:"POST",body:upload});const result=await response.json();if(!response.ok)throw new Error(result?.error?.message||"Upload failed");setMediaUrl(result.secure_url);setMediaPublicId(result.public_id);}catch(e){setError(e instanceof Error?e.message:"Upload failed");}finally{setUploading(false);}}
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");try{const form=new FormData(event.currentTarget);const supabase=createSupabaseBrowserClient();const {data:userData}=await supabase.auth.getUser();if(!userData.user){location.href="/login";return;}const title=value(form,"title");if(!title)throw new Error("Post title is required.");const collaborators=value(form,"instagram_collaborators").split(",").map(x=>x.trim().replace(/^@/,"")).filter(Boolean);const {data:post,error:insertError}=await supabase.from("posts").insert({title,content:value(form,"content")||null,facebook_caption:value(form,"facebook_caption")||null,instagram_caption:value(form,"instagram_caption")||null,linkedin_caption:value(form,"linkedin_caption")||null,google_business_caption:value(form,"google_business_caption")||null,hashtags:value(form,"hashtags")||null,link_url:value(form,"link_url")||null,media_url:mediaUrl||null,media_public_id:mediaPublicId||null,media_type:mediaType,instagram_collaborators:collaborators,status:"draft",created_by:userData.user.id}).select("id").single();if(insertError)throw insertError;const rows=channels.map(c=>({post_id:post.id,channel:c.id,enabled:selected.includes(c.id),status:selected.includes(c.id)?"pending":"not_selected"}));const {error:pubError}=await supabase.from("post_publications").insert(rows);if(pubError)throw pubError;location.href=`/posts/${post.id}`;}catch(e){setError(e instanceof Error?e.message:"Unable to save post");}finally{setSaving(false);}}
 return <main className="shell"><section className="hero"><div><p className="eyebrow">Publishing Studio</p><h1>Create Post</h1><p className="lede">Publish regular content independently from events.</p></div></section><form className="panel eventForm" onSubmit={save}>
 <div className="formSection"><p className="eyebrow">1. Content</p><h2>Master post</h2><label>Internal post title<input name="title" required placeholder="September healing reminder" /></label><label>Master content<textarea name="content" rows={7} placeholder="Write the main message..." /></label><label>Link / CTA URL<input name="link_url" type="url" placeholder="https://..." /></label></div>
 <div className="formSection"><p className="eyebrow">2. Media</p><h2>Image or video</h2><div className="uploadBox"><strong>Upload image or video</strong><input type="file" accept="image/*,video/*" onChange={uploadMedia} disabled={uploading}/>{uploading?<small>Uploading...</small>:null}{mediaUrl?<p className="formSuccess">{mediaType} uploaded successfully.</p>:null}</div></div>
 <div className="formSection"><p className="eyebrow">3. Platform copy</p><h2>Customize each destination</h2><label>Facebook<textarea name="facebook_caption" rows={5}/></label><label>Instagram<textarea name="instagram_caption" rows={6}/></label><label>LinkedIn<textarea name="linkedin_caption" rows={5}/></label><label>Google Business<textarea name="google_business_caption" rows={5}/></label><label>Hashtags<input name="hashtags" placeholder="#ExperienceHealing #Wellness"/></label></div>
 <div className="formSection"><p className="eyebrow">4. Collaboration</p><h2>Supported collaborators</h2><label>Instagram collaborator usernames<input name="instagram_collaborators" placeholder="username1, username2"/></label><p className="mutedText">Stored separately from the caption. Collaboration will only be sent when the connected platform/API supports it; otherwise normal publishing still works.</p></div>
 <div className="formSection"><p className="eyebrow">5. Destinations</p><h2>Select platforms</h2><div className="channelGrid">{channels.map(c=><button key={c.id} type="button" className={`channel channelButton ${selected.includes(c.id)?"selected":""}`} onClick={()=>toggle(c.id)}><strong>{c.label}</strong><small>{selected.includes(c.id)?"Selected":"Not selected"}</small></button>)}</div></div>
 {error?<p className="formError">{error}</p>:null}<div className="formActions"><button className="primaryButton" disabled={saving||uploading} type="submit">{saving?"Saving...":"Save & Review Post"}</button></div></form></main>;
}
