import Link from "next/link";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export default async function PostReviewPage({ params }: { params: Promise<{ id: string }> }) {
 const {id}=await params; const supabase=await createSupabaseServerClient(); const {data:post}=await supabase.from("posts").select("*").eq("id",id).single(); const {data:publications}=await supabase.from("post_publications").select("channel,enabled,status,external_url,last_error").eq("post_id",id);
 if(!post)return <main className="shell"><section className="panel"><h1>Post not found</h1></section></main>;
 return <main className="shell"><section className="hero"><div><p className="eyebrow">Publishing Studio · Review</p><h1>{post.title}</h1><p className="lede">Review this post before publishing. Live publishing APIs will be connected in the next implementation step.</p></div><Link className="secondaryButton inlineButton" href="/posts">All Posts</Link></section>
 <section className="panel"><div className="twoCol"><div><p className="eyebrow">Master content</p><p style={{whiteSpace:"pre-wrap"}}>{post.content||"No master content."}</p>{post.link_url?<p><a href={post.link_url} target="_blank" rel="noreferrer">Open CTA link</a></p>:null}</div><div><p className="eyebrow">Media</p>{post.media_url?<><p>{post.media_type === "video" ? "Video uploaded" : "Image uploaded"}</p><a href={post.media_url} target="_blank" rel="noreferrer">Open media</a></>:<p>No media uploaded.</p>}</div></div></section>
 <section className="panel"><p className="eyebrow">Platform copy</p><div className="reviewCopy"><h3>Facebook</h3><p style={{whiteSpace:"pre-wrap"}}>{post.facebook_caption||post.content||"—"}</p><h3>Instagram</h3><p style={{whiteSpace:"pre-wrap"}}>{post.instagram_caption||post.content||"—"}</p><h3>LinkedIn</h3><p style={{whiteSpace:"pre-wrap"}}>{post.linkedin_caption||post.content||"—"}</p><h3>Google Business</h3><p style={{whiteSpace:"pre-wrap"}}>{post.google_business_caption||post.content||"—"}</p><h3>Hashtags</h3><p>{post.hashtags||"—"}</p></div></section>
 <section className="panel"><p className="eyebrow">Collaboration</p><h2>Instagram collaborators</h2><p>{post.instagram_collaborators?.length?post.instagram_collaborators.map((x:string)=>`@${x}`).join(", "):"No collaborators selected."}</p><p className="mutedText">Collaborator requests will only be used where the connected API supports them.</p></section>
 <section className="panel"><p className="eyebrow">Destinations</p><h2>Publishing readiness</h2><div className="publishList">{(publications||[]).map((p)=><div className="publishChannel" key={p.channel}><div className="publishRow"><div><strong>{p.channel.replace("google_business","Google Business")}</strong><small>{p.enabled?"Selected":"Not selected"}</small></div><span className={`statusPill status-${p.status}`}>{p.status}</span></div>{p.last_error?<p className="channelError">{p.last_error}</p>:null}</div>)}</div><div className="publishNotice"><strong>Publishing controls are intentionally not active yet.</strong><p>This first slice creates the independent Posts module, database records, image/video uploads, platform copy, collaborator data and review flow without risking an accidental live post.</p></div></section>
 </main>;
}
